server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      # uri: mongodb://mongo:mongo@containers-us-west-60.railway.app:6843/microservices?authSource=admin
      uri: mongodb://mongo:uiYWYK5CNBevcnRrzoXs@containers-us-west-60.railway.app:6843/microservices?authSource=admin
      database: microservices
  # config:
  #   import: configserver:http://localhost:8085

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    refresh:
      enable: true
    service-url:
      defaultZone:  https://serviceregitsry-production.up.railway.app/eureka